[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"

# Remappings are now handled in remappings.txt for robustness

[rpc_endpoints]
amoy = "https://rpc-amoy.polygon.technology/"

[etherscan]
amoy = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
