services:
  postgres:
    image: postgres:14
    container_name: graph-postgres
    restart: always
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graph-node
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graph-node -d graph-node"]
      interval: 5s
      timeout: 5s
      retries: 5

  graph-node:
    image: graphprotocol/graph-node:latest
    container_name: graph-node
    restart: always
    ports:
      - '8000:8000' # GraphQL API
      - '8001:8001' # JSON-RPC
      - '8020:8020' # Indexer metrics
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: password
      postgres_db: graph-node
      # This is the key change: Point to a reliable public IPFS gateway
      ipfs_uri: 'https://api.thegraph.com/ipfs/'
      ethereum: 'amoy:https://polygon-amoy.g.alchemy.com/v2/ZKuN-EIxnaeRZsy6IgZXs'
      GRAPH_LOG: info

# Define the named volumes
volumes:
  postgres-data:

